"use client"

/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/bO0v5gE9g7V
 */
import { CardTitle, CardHeader, CardContent, CardFooter, Card } from "@/components/ui/card"
import { Button } from "@/components/ui/button"
import Script from "next/script"
import { NewsletterSignup } from "@/components/newsletter-signup"

export function MembershipSection() {
  return (
    <div className="bg-white dark:bg-gray-950 py-12">
      <div className="container mx-auto px-4">
        <div className="text-center mb-12">
          <h2 className="text-4xl font-bold tracking-tight text-gray-900 dark:text-gray-50">
            Memberships & <span className="gradient-sage-text">Class Passes</span>
          </h2>
        </div>
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
          <Card className="border-2 border-gray-200 dark:border-gray-800 rounded-lg shadow-lg flex flex-col">
            <CardHeader>
              <CardTitle>1 Month Membership</CardTitle>
            </CardHeader>
            <CardContent className="flex-grow">
              <p className="text-4xl font-bold">$125/month*</p>
              <p className="text-sm text-gray-500 dark:text-gray-400 mt-2">* Yoga Only</p>
              <p className="mt-4">Student/Senior price $108/month</p>
              <p className="text-sm text-gray-600 dark:text-gray-300 mt-2">Use code STUDENTONE1 at checkout</p>
              <p className="text-sm text-gray-500 dark:text-gray-400 mt-2">No further commitment required</p>
            </CardContent>
            <CardFooter>
              <Button className="w-full gradient-sage text-white" asChild>
                <a href="https://clients.mindbodyonline.com/classic/ws?studioid=11233&stype=40&prodId=193" target="_blank" rel="noopener noreferrer">Buy Membership</a>
              </Button>
            </CardFooter>
          </Card>
          <Card className="border-2 border-purple-500 dark:border-purple-400 rounded-lg shadow-lg relative flex flex-col">
            <div className="absolute top-0 right-0 bg-purple-500 text-white text-xs font-bold px-3 py-1 rounded-bl-lg">
              Popular
            </div>
            <CardHeader>
              <CardTitle>Monthly Membership</CardTitle>
            </CardHeader>
            <CardContent className="flex-grow">
              <p className="text-4xl font-bold">$115/month*</p>
              <p className="text-sm text-gray-500 dark:text-gray-400 mt-2">* Yoga Only</p>
              <p className="mt-4">Student/Senior price $89/month</p>
              <p className="text-sm text-gray-600 dark:text-gray-300 mt-2">Use code STUDENT1 at checkout</p>
              <p className="text-sm text-gray-500 dark:text-gray-400 mt-2">Minimum 4 month commitment</p>
            </CardContent>
            <CardFooter>
              <Button className="w-full gradient-sage text-white" asChild>
                <a href="https://clients.mindbodyonline.com/classic/ws?studioid=11233&stype=40&prodId=156" target="_blank" rel="noopener noreferrer">Buy Membership</a>
              </Button>
            </CardFooter>
          </Card>
          <Card className="border-2 border-gray-200 dark:border-gray-800 rounded-lg shadow-lg flex flex-col">
            <CardHeader>
              <CardTitle>Take 5 Membership</CardTitle>
            </CardHeader>
            <CardContent className="flex-grow">
              <p className="text-4xl font-bold">$89/Month*</p>
              <p className="text-sm text-gray-500 dark:text-gray-400 mt-2">*Includes Pilates</p>
              <p className="mt-4">Auto-renews monthly</p>
              <p className="text-sm text-gray-500 dark:text-gray-400">4 month commitment</p>
            </CardContent>
            <CardFooter>
              <div 
                className="w-full"
                dangerouslySetInnerHTML={{
                  __html: `<healcode-widget data-version="0.2" data-link-class="healcode-contract-text-link w-full gradient-sage text-white inline-flex items-center justify-center whitespace-nowrap rounded-md text-sm font-medium ring-offset-background transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-50 h-10 px-4 py-2 cursor-pointer" data-site-id="1889" data-mb-site-id="11233" data-service-id="163" data-bw-identity-site="true" data-type="contract-link" data-inner-html="Buy Membership"></healcode-widget>`
                }}
              />
            </CardFooter>
          </Card>
        </div>
        <div className="mt-16 bg-gray-100 dark:bg-gray-900 p-8 rounded-lg">
          <div className="text-center max-w-3xl mx-auto">
            <h2 className="text-3xl md:text-4xl font-bold tracking-tight text-gray-900 dark:text-gray-50 mb-4">
              Your First Two Weeks for Only $39
            </h2>
            <p className="mt-4 text-lg text-gray-600 dark:text-gray-400 mb-6">
              Our aim is to serve you and what you need. We have teachers of all different backgrounds and trainings, and offer classes across the wide spectrum of yoga. Try them all with your intro pass and find what you love.
            </p>
            <div className="mt-6">
              <div 
                dangerouslySetInnerHTML={{
                  __html: `<healcode-widget data-version="0.2" data-link-class="healcode-pricing-option-text-link inline-flex items-center justify-center whitespace-nowrap rounded-md text-lg font-medium gradient-sage hover:opacity-90 text-white px-8 py-4 shadow-lg cursor-pointer" data-site-id="1889" data-mb-site-id="11233" data-service-id="1364" data-bw-identity-site="true" data-type="pricing-link" data-inner-html="Buy Intro Pass"></healcode-widget>`
                }}
              />
            </div>
          </div>
        </div>
        <div className="text-center mt-16">
          <h3 className="text-3xl font-bold tracking-tight text-gray-900 dark:text-gray-50">Yoga + Pilates</h3>
        </div>
        <div className="grid grid-cols-1 md:grid-cols-2 gap-8 mt-8">
          <Card className="border-2 border-gray-200 dark:border-gray-800 rounded-lg shadow-lg">
            <CardHeader>
              <CardTitle>1 Month Membership</CardTitle>
            </CardHeader>
            <CardContent>
              <p className="text-4xl font-bold">$159/month</p>
              <p className="text-sm text-gray-500 dark:text-gray-400 mt-2">Unlimited Yoga + Pilates</p>
              <p className="mt-4">Student/Senior price $142/month</p>
              <p className="text-sm text-gray-600 dark:text-gray-300 mt-2">Use code STUDENTONE1 at checkout</p>
              <p className="text-sm text-gray-500 dark:text-gray-400 mt-2">No further commitment required, auto-renews until cancelled</p>
            </CardContent>
            <CardFooter>
              <Button className="w-full gradient-sage text-white" asChild>
                <a href="https://clients.mindbodyonline.com/classic/ws?studioid=11233&stype=40&prodId=189" target="_blank" rel="noopener noreferrer">Buy Membership</a>
              </Button>
            </CardFooter>
          </Card>
          <Card className="border-2 border-gray-200 dark:border-gray-800 rounded-lg shadow-lg">
            <CardHeader>
              <CardTitle>Monthly Membership</CardTitle>
            </CardHeader>
            <CardContent>
              <p className="text-4xl font-bold">$149/month</p>
              <p className="text-sm text-gray-500 dark:text-gray-400 mt-2">Unlimited Yoga + Pilates</p>
              <p className="mt-4">Student/Senior price $123/month</p>
              <p className="text-sm text-gray-600 dark:text-gray-300 mt-2">Use code STUDENT1 at checkout</p>
              <p className="text-sm text-gray-500 dark:text-gray-400 mt-2">Minimum 4 month commitment, auto-renews until cancelled </p>
            </CardContent>
            <CardFooter>
              <Button className="w-full gradient-sage text-white" asChild>
                <a href="https://clients.mindbodyonline.com/classic/ws?studioid=11233&stype=40&prodId=190" target="_blank" rel="noopener noreferrer">Buy Membership</a>
              </Button>
            </CardFooter>
          </Card>
        </div>
        <div className="text-center mt-16">
          <h3 className="text-3xl font-bold tracking-tight text-gray-900 dark:text-gray-50">Class Passes</h3>
        </div>
        <div className="grid grid-cols-1 md:grid-cols-2 gap-8 mt-8">
          <Card className="border-2 border-gray-200 dark:border-gray-800 rounded-lg shadow-lg">
            <CardHeader>
              <CardTitle>Single Class</CardTitle>
            </CardHeader>
            <CardContent>
              <p className="text-4xl font-bold">$25</p>
              <p className="mt-4">$18 Student/Senior Price</p>
              <p className="text-sm text-gray-500 dark:text-gray-400">Single Use, 1 Year Expiry</p>
            </CardContent>
            <CardFooter>
              <div 
                className="w-full"
                dangerouslySetInnerHTML={{
                  __html: `<healcode-widget data-version="0.2" data-link-class="healcode-pricing-option-text-link w-full gradient-sage text-white inline-flex items-center justify-center whitespace-nowrap rounded-md text-sm font-medium ring-offset-background transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-50 h-10 px-4 py-2 cursor-pointer" data-site-id="1889" data-mb-site-id="11233" data-service-id="289" data-bw-identity-site="true" data-type="pricing-link" data-inner-html="Buy Now"></healcode-widget>`
                }}
              />
            </CardFooter>
          </Card>
          <Card className="border-2 border-gray-200 dark:border-gray-800 rounded-lg shadow-lg">
            <CardHeader>
              <CardTitle>10 Class Pass</CardTitle>
            </CardHeader>
            <CardContent>
              <p className="text-4xl font-bold">$189</p>
              <p className="mt-4">$149 Student/Senior Price</p>
              <p className="text-sm text-gray-500 dark:text-gray-400">Expires After 1 Year</p>
            </CardContent>
            <CardFooter>
              <div 
                className="w-full"
                dangerouslySetInnerHTML={{
                  __html: `<healcode-widget data-version="0.2" data-link-class="healcode-pricing-option-text-link w-full gradient-sage text-white inline-flex items-center justify-center whitespace-nowrap rounded-md text-sm font-medium ring-offset-background transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-50 h-10 px-4 py-2 cursor-pointer" data-site-id="1889" data-mb-site-id="11233" data-service-id="291" data-bw-identity-site="true" data-type="pricing-link" data-inner-html="Buy Now"></healcode-widget>`
                }}
              />
            </CardFooter>
          </Card>
        </div>
        <div className="text-center mt-16 bg-gray-100 dark:bg-gray-900 p-8 rounded-lg">
          <h3 className="text-3xl font-bold tracking-tight text-gray-900 dark:text-gray-50">Corporate Membership</h3>
          <p className="mt-4 text-lg text-gray-600 dark:text-gray-400">
            We have over 100 corporate members. Is your employer one of them? Click the button below to ask if your
            company is partnered with us already, or to inquire about setting up a new corporate partnership.
          </p>
          <Button className="mt-6 gradient-sage text-white" asChild>
            <a href="mailto:info@shantihotyoga.ca?subject=corporate%20partner%20request">Contact Us</a>
          </Button>
        </div>
        <div className="mt-16">
          <NewsletterSignup
            title="Stay in the loop"
            subtitle="Sign up with your email address to receive news and updates."
            tags={["website-newsletter"]}
          />
        </div>
      </div>
      
      {/* Load HealCode script using Next.js Script component */}
      <Script
        src="https://widgets.mindbodyonline.com/javascripts/healcode.js"
        strategy="afterInteractive"
        onLoad={() => {
          console.log('HealCode script loaded successfully for membership')
        }}
        onError={(e) => {
          console.error('Failed to load HealCode script for membership:', e)
        }}
      />
    </div>
  )
} 