/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/bO0v5gE9g7V
 */
import { CardTitle, CardHeader, CardContent, CardFooter, Card } from "@/components/ui/card"
import { Button } from "@/components/ui/button"

export function MembershipSection() {
  return (
    <div className="bg-white dark:bg-gray-950 py-12">
      <div className="container mx-auto px-4">
        <div className="text-center mb-12">
          <h2 className="text-4xl font-bold tracking-tight text-gray-900 dark:text-gray-50">
            Memberships & <span className="gradient-sage-text">Class Passes</span>
          </h2>
        </div>
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
          <Card className="border-2 border-gray-200 dark:border-gray-800 rounded-lg shadow-lg">
            <CardHeader>
              <CardTitle>1 Month Membership</CardTitle>
            </CardHeader>
            <CardContent>
              <p className="text-4xl font-bold">$125/month*</p>
              <p className="text-sm text-gray-500 dark:text-gray-400 mt-2">* Yoga Only</p>
              <p className="mt-4">Student/Senior price $108/month</p>
              <p className="text-sm text-gray-500 dark:text-gray-400">No further commitment required</p>
            </CardContent>
            <CardFooter>
              <Button className="w-full gradient-sage text-white" asChild>
                {/* @ts-expect-error - Mindbody widget */}
                <healcode-widget
                  data-version="0.2"
                  data-link-class="healcode-contract-text-link w-full h-full block flex items-center justify-center"
                  data-site-id="1889"
                  data-mb-site-id="11233"
                  data-service-id="193"
                  data-bw-identity-site="false"
                  data-type="contract-link"
                  data-inner-html="Buy Membership"
                />
              </Button>
            </CardFooter>
          </Card>
          <Card className="border-2 border-purple-500 dark:border-purple-400 rounded-lg shadow-lg relative">
            <div className="absolute top-0 right-0 bg-purple-500 text-white text-xs font-bold px-3 py-1 rounded-bl-lg">
              Popular
            </div>
            <CardHeader>
              <CardTitle>Monthly Membership</CardTitle>
            </CardHeader>
            <CardContent>
              <p className="text-4xl font-bold">$115/month*</p>
              <p className="text-sm text-gray-500 dark:text-gray-400 mt-2">* Yoga Only</p>
              <p className="mt-4">Student/Senior price $89/month</p>
              <p className="text-sm text-gray-500 dark:text-gray-400">Minimum 4 month commitment</p>
            </CardContent>
            <CardFooter>
              <Button className="w-full gradient-sage text-white" asChild>
                {/* @ts-expect-error - Mindbody widget */}
                <healcode-widget
                  data-version="0.2"
                  data-link-class="healcode-contract-text-link w-full h-full block flex items-center justify-center"
                  data-site-id="1889"
                  data-mb-site-id="11233"
                  data-service-id="156"
                  data-bw-identity-site="false"
                  data-type="contract-link"
                  data-inner-html="Buy Membership"
                />
              </Button>
            </CardFooter>
          </Card>
          <Card className="border-2 border-gray-200 dark:border-gray-800 rounded-lg shadow-lg">
            <CardHeader>
              <CardTitle>Take 5 Membership</CardTitle>
            </CardHeader>
            <CardContent>
              <p className="text-4xl font-bold">$79/Month*</p>
              <p className="text-sm text-gray-500 dark:text-gray-400 mt-2">*Includes Pilates</p>
              <p className="mt-4">Auto-renews monthly</p>
              <p className="text-sm text-gray-500 dark:text-gray-400">4 month commitment</p>
            </CardContent>
            <CardFooter>
              <Button className="w-full gradient-sage text-white">Buy membership</Button>
            </CardFooter>
          </Card>
        </div>
        <div className="text-center mt-16">
          <h3 className="text-3xl font-bold tracking-tight text-gray-900 dark:text-gray-50">Yoga + Pilates</h3>
        </div>
        <div className="grid grid-cols-1 md:grid-cols-2 gap-8 mt-8">
          <Card className="border-2 border-gray-200 dark:border-gray-800 rounded-lg shadow-lg">
            <CardHeader>
              <CardTitle>1 Month Membership</CardTitle>
            </CardHeader>
            <CardContent>
              <p className="text-4xl font-bold">$159/month</p>
              <p className="text-sm text-gray-500 dark:text-gray-400 mt-2">Unlimited Yoga + Pilates</p>
              <p className="mt-4">Student/Senior price $142/month</p>
              <p className="text-sm text-gray-500 dark:text-gray-400">No further commitment required, auto-renews until cancelled</p>
            </CardContent>
            <CardFooter>
              <Button className="w-full gradient-sage text-white">Buy membership</Button>
            </CardFooter>
          </Card>
          <Card className="border-2 border-gray-200 dark:border-gray-800 rounded-lg shadow-lg">
            <CardHeader>
              <CardTitle>Monthly Membership</CardTitle>
            </CardHeader>
            <CardContent>
              <p className="text-4xl font-bold">$149/month</p>
              <p className="text-sm text-gray-500 dark:text-gray-400 mt-2">Unlimited Yoga + Pilates</p>
              <p className="mt-4">Student/Senior price $123/month</p>
              <p className="text-sm text-gray-500 dark:text-gray-400">Minimum 4 month commitment, auto-renews until cancelled </p>
            </CardContent>
            <CardFooter>
              <Button className="w-full gradient-sage text-white">Buy membership</Button>
            </CardFooter>
          </Card>
        </div>
        <div className="text-center mt-16">
          <h3 className="text-3xl font-bold tracking-tight text-gray-900 dark:text-gray-50">Class Passes</h3>
        </div>
        <div className="grid grid-cols-1 md:grid-cols-2 gap-8 mt-8">
          <Card className="border-2 border-gray-200 dark:border-gray-800 rounded-lg shadow-lg">
            <CardHeader>
              <CardTitle>Single Class</CardTitle>
            </CardHeader>
            <CardContent>
              <p className="text-4xl font-bold">$25</p>
              <p className="mt-4">$18 Student/Senior Price</p>
            </CardContent>
            <CardFooter>
              <Button className="w-full gradient-sage text-white">Buy</Button>
            </CardFooter>
          </Card>
          <Card className="border-2 border-gray-200 dark:border-gray-800 rounded-lg shadow-lg">
            <CardHeader>
              <CardTitle>10 Class Pass</CardTitle>
            </CardHeader>
            <CardContent>
              <p className="text-4xl font-bold">$179</p>
              <p className="mt-4">$139 Student/Senior Price</p>
              <p className="text-sm text-gray-500 dark:text-gray-400">Expires After 1 Year</p>
            </CardContent>
            <CardFooter>
              <Button className="w-full gradient-sage text-white">Buy</Button>
            </CardFooter>
          </Card>
        </div>
        <div className="text-center mt-16 bg-gray-100 dark:bg-gray-900 p-8 rounded-lg">
          <h3 className="text-3xl font-bold tracking-tight text-gray-900 dark:text-gray-50">Corporate Membership</h3>
          <p className="mt-4 text-lg text-gray-600 dark:text-gray-400">
            We have over 100 corporate members. Is your employer one of them? Click the button below to ask if your
            company is partnered with us already, or to inquire about setting up a new corporate partnership.
          </p>
          <Button className="mt-6 gradient-sage text-white">Contact Us</Button>
        </div>
        <div className="text-center mt-16">
          <h3 className="text-3xl font-bold tracking-tight text-gray-900 dark:text-gray-50">Stay in the loop</h3>
          <p className="mt-4 text-lg text-gray-600 dark:text-gray-400">
            Sign up with your email address to receive news and updates.
          </p>
          <div className="mt-6 flex justify-center">
            <input
              className="w-full max-w-sm p-2 border border-gray-300 rounded-l-md dark:bg-gray-800 dark:border-gray-700 dark:text-gray-50"
              placeholder="Email Address"
              type="email"
            />
            <Button className="rounded-r-md gradient-sage text-white">Sign Up</Button>
          </div>
        </div>
      </div>
    </div>
  )
} 